"""
policy_qa.tool
================

A grounded citation-finder over the playbook's own governance corpus
(03-governance/*.md). This is deliberately lexical retrieval, not an
embeddings/vector search and not an LLM answering from memory: for a policy
question, "here are the three sections that actually say this, go read
them" is more trustworthy than a fluent paraphrase that might be subtly
wrong about an EU AI Act deadline or a pay-equity rule. The calling agent
can use the returned sections to compose a plain-language answer, but the
citations, and the disclaimer, are non-negotiable and generated by this
module, not left to the agent's discretion.

Repo root resolution: this module is meant to live at
`10-mcp-agents/policy_qa/tool.py` inside the main playbook repo, two levels
below the repo root where `03-governance/` lives. `_find_repo_root` walks
up from this file looking for a `03-governance` directory so it works
correctly at that real path, while still accepting an explicit `repo_root`
override for testing against a fixture corpus instead of the real one.
"""

from __future__ import annotations

import re
from pathlib import Path

GOVERNANCE_DIRNAME = "03-governance"

_STOPWORDS = {
    "the", "and", "for", "with", "you", "your", "our", "a", "an", "to", "of",
    "in", "on", "is", "are", "will", "be", "or", "as", "at", "by", "this",
    "that", "we", "us", "it", "its", "their", "they", "who", "have", "has",
    "what", "how", "do", "does", "can", "i", "my",
}

_NAVIGATIONAL_HEADINGS = {"cross-links", "cross links", "see also", "references", "related", "further reading"}

NOT_LEGAL_ADVICE_DISCLAIMER = (
    "This is a citation finder over the playbook's governance documents, not legal advice and "
    "not a policy decision. For anything with real legal exposure (a specific EU AI Act filing, "
    "a pay-equity determination, an incident with regulatory implications) escalate to Legal or "
    "Privacy directly, the citations below are a starting point for that conversation, not a "
    "substitute for it."
)


class GovernanceCorpusNotFoundError(FileNotFoundError):
    pass


def _find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / GOVERNANCE_DIRNAME).is_dir():
            return candidate
    raise GovernanceCorpusNotFoundError(
        f"Could not find a '{GOVERNANCE_DIRNAME}' directory above {start}. "
        "Pass repo_root explicitly if this module isn't running from inside the playbook repo."
    )


def _split_sections(markdown_text: str, source_file: str) -> list[dict]:
    """Split a markdown file into sections at ## AND ### boundaries.

    Splitting at ### too (not just ##) matters in practice: several docs in
    this corpus structure a checklist as one ## with numbered ### subitems
    (e.g. vendor-intake-checklist.md's "Required artifacts" -> "1.
    Instructions for use", "2. ...", etc). Chunking only at ## merges all of
    those into one long section, which then wins retrieval by accident on
    any query that happens to overlap several of its subitems, crowding out
    a shorter, more precisely on-topic section elsewhere. Splitting at ###
    too gives each subitem its own citable chunk. A file with no ##/###
    headers at all becomes a single section using the filename as its
    heading, so nothing is silently dropped.
    """
    lines = markdown_text.splitlines()
    sections: list[dict] = []
    current_h2 = source_file
    current_heading = source_file
    current_lines: list[str] = []

    def _flush():
        text = "\n".join(current_lines).strip()
        if text:
            sections.append({"heading": current_heading, "text": text, "source_file": source_file})

    for line in lines:
        if line.startswith("## "):
            _flush()
            current_h2 = line[3:].strip()
            current_heading = current_h2
            current_lines = []
        elif line.startswith("### "):
            _flush()
            h3 = line[4:].strip()
            # Keep the parent ## for context in the citation ("Required
            # artifacts > 1. Instructions for use") rather than just the
            # bare subitem, which can be uninformative on its own (many
            # checklists number their subitems "1.", "2.", ...).
            current_heading = f"{current_h2} > {h3}" if current_h2 != source_file else h3
            current_lines = []
        elif line.startswith("# "):
            pass  # doc title, handled separately by _doc_title(); not a section boundary
        else:
            current_lines.append(line)
    _flush()
    return sections


def _doc_title(markdown_text: str, fallback: str) -> str:
    for line in markdown_text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def load_governance_docs(repo_root: Path | None = None) -> list[dict]:
    root = repo_root or _find_repo_root(Path(__file__).parent)
    gov_dir = root / GOVERNANCE_DIRNAME
    if not gov_dir.is_dir():
        raise GovernanceCorpusNotFoundError(f"{gov_dir} does not exist")

    sections: list[dict] = []
    for md_file in sorted(gov_dir.glob("*.md")):
        text = md_file.read_text(encoding="utf-8")
        doc_title = _doc_title(text, md_file.stem)
        for section in _split_sections(text, md_file.name):
            section["doc_title"] = doc_title
            sections.append(section)
    return sections


def _keywords(text: str) -> set[str]:
    words = re.findall(r"[a-zA-Z][a-zA-Z\-]+", text.lower())
    return {w for w in words if len(w) >= 3 and w not in _STOPWORDS}


def search_policy(question: str, repo_root: Path | None = None, top_k: int = 3) -> dict:
    """Return the top_k governance sections most relevant to a question, by
    keyword overlap, plus the mandatory disclaimer. Returns an empty result
    list (never a fabricated answer) when nothing in the corpus overlaps."""
    q_keywords = _keywords(question)
    if not q_keywords:
        return {"question": question, "results": [], "disclaimer": NOT_LEGAL_ADVICE_DISCLAIMER}

    sections = load_governance_docs(repo_root)
    scored = []
    for section in sections:
        # Score against heading + body first -- this is what should usually
        # decide it. Doc title and filename are folded in too, at lower
        # weight, purely to break the specific failure mode where a
        # "Cross-links" section that happens to namedrop another file (e.g.
        # "see incident-report-template.md") outscores that file's own,
        # actually-relevant section just because the real section doesn't
        # repeat its own document's subject word in every chunk.
        primary_keywords = _keywords(section["heading"] + " " + section["text"])
        filename_stem = section["source_file"].rsplit(".", 1)[0].replace("-", " ").replace("_", " ")
        context_keywords = _keywords(section.get("doc_title", "") + " " + filename_stem)

        primary_overlap = q_keywords & primary_keywords
        context_overlap = (q_keywords & context_keywords) - primary_overlap
        score = len(primary_overlap) + 0.25 * len(context_overlap)

        # A "Cross-links" (or similar navigational) section is a list of
        # pointers to other files, not an answer. It will often score well
        # by accident, it literally namedrops other documents' subjects,
        # e.g. "see incident-report-template.md, this is an automatic Sev
        # 1" inside pay-equity-governance.md's own cross-links. Without this
        # penalty that sentence can outrank incident-report-template.md's
        # actual severity-scale section for a question about severity, which
        # sends someone to the wrong document. Caught by re-running this
        # tool against the real governance corpus, not just the unit fixture.
        if section["heading"].strip().lower() in _NAVIGATIONAL_HEADINGS:
            score *= 0.3

        overlap = primary_overlap | context_overlap
        if overlap:
            scored.append((score, overlap, section))

    scored.sort(key=lambda t: t[0], reverse=True)
    top = scored[:top_k]

    results = [
        {
            "source_file": section["source_file"],
            "heading": section["heading"],
            "matched_terms": sorted(overlap),
            "excerpt": (section["text"][:600] + "...") if len(section["text"]) > 600 else section["text"],
        }
        for _, overlap, section in top
    ]

    return {
        "question": question,
        "results": results,
        "no_match": len(results) == 0,
        "disclaimer": NOT_LEGAL_ADVICE_DISCLAIMER,
    }
